name: testing
on:
  push:
    branches: [main]
jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build image
        run: docker build -t mi-imagen:latest .

      - name: run alpine container
        run: docker run -d --name alpine-test alpine sh -c "while true; do sleep 60; done"

      - name: run tests inside container (shell)
        run: |
          docker exec alpine-test sh -lc "printf 'contenido de prueba\n' > ejemplo.txt && ls -la"
